#!/bin/bash

# Install essential things for linux desktop
# - caps to ctrl
# - monospace font (Cica)
# for more enrivonment-specific things, see directories `gnome` and `i3`.

# caps to ctrl
grep "ctrl:nocaps" /etc/default/keyboard > /dev/null
if [ "$?" = 0 ]; then
    echo "Caps to Ctrl is already done."
else
    sudo su -c "sed -iE 's/^XKBOPTIONS/#XKBOPTIONS/' /etc/default/keyboard"
    sudo su -c "echo XKBOPTIONS=ctrl:nocaps >> /etc/default/keyboard"
fi

# install Cica font
fc-list | grep Cica > /dev/null
if [ "$?" = 0 ]; then
    echo "Cica font is already installed."
else
    local cica_v=v4.1.2
    local cica_fn=Cica_${cica_v}.zip
    local cica_dir=Cica_${cica_v}

    echo "Download and install Cica ${cica_v}..."

    curl -SL https://github.com/miiton/Cica/releases/download/${cica_v}/${cica_fn} -o ${cica_fn}
    unzip ${cica_fn} -d ${cica_dir}
    mkdir -p ~/.local/share/fonts
    mv ${cica_dir}/Cica*.ttf ~/.local/share/fonts/
    fc-cache -fv
    rm -r ${cica_fn} ${cica_dir}
fi
