#!/bin/bash

# Install essential things for linux desktop
# - caps to ctrl
# - monospace font (Cica)
# - urxvt launcher at ./bin/urxvt_local
# for more enrivonment-specific things, see directories `gnome` and `i3`.

# caps to ctrl
grep "ctrl:nocaps" /etc/default/keyboard > /dev/null
if [ "$?" = 0 ]; then
    echo "Caps to Ctrl is already done."
else
    sudo su -c "sed -iE 's/^XKBOPTIONS/#XKBOPTIONS/' /etc/default/keyboard"
    sudo su -c "echo XKBOPTIONS=ctrl:nocaps >> /etc/default/keyboard"
fi

# install Cica font
fc-list | grep Cica > /dev/null
if [ "$?" = 0 ]; then
    echo "Cica font is already installed."
else
    cica_v=v4.1.2
    cica_fn=Cica_${cica_v}.zip
    cica_dir=Cica_${cica_v}

    echo "Download and install Cica ${cica_v}..."

    curl -SL https://github.com/miiton/Cica/releases/download/${cica_v}/${cica_fn} -o ${cica_fn}
    unzip ${cica_fn} -d ${cica_dir}
    mkdir -p ~/.local/share/fonts
    mv ${cica_dir}/Cica*.ttf ~/.local/share/fonts/
    fc-cache -fv
    rm -r ${cica_fn} ${cica_dir}
fi

# make bin/urxvt_local
fpath=~/dotfiles/bin/urxvt_local
if [ -e $fpath ]; then
    echo "${fpath} is already there."
else
    cat << EOS > ${fpath}
#!/bin/bash
# you can put some options for local machine, since this file is git-ignored.
urxvt_auto
EOS
    chmod +x ${fpath}
fi
