#!/bin/zsh

# Install things for Linux desktop

# Common things
## XKBOPTIONS for caps to ctrl
grep "ctrl:nocaps" /etc/default/keyboard > /dev/null
if [ "$?" = 0 ]; then
    echo "Caps to Ctrl is already done."
else
    sudo su -c "sed -iE 's/^XKBOPTIONS/#XKBOPTIONS/' /etc/default/keyboard"
    sudo su -c "echo XKBOPTIONS=ctrl:nocaps >> /etc/default/keyboard"
fi

## install Cica font
fc-list | grep Cica > /dev/null
if [ "$?" = 0 ]; then
    echo "Cica font is already installed."
else
    cica_v=v4.1.2
    cica_fn=Cica_${cica_v}.zip
    cica_dir=Cica_${cica_v}

    echo "Download and install Cica ${cica_v}..."

    curl -SL https://github.com/miiton/Cica/releases/download/${cica_v}/${cica_fn} -o ${cica_fn}
    unzip ${cica_fn} -d ${cica_dir}
    mkdir -p ~/.local/share/fonts
    mv ${cica_dir}/Cica*.ttf ~/.local/share/fonts/
    fc-cache -fv
    rm -r ${cica_fn} ${cica_dir}
fi

## make bin/urxvt_local
fpath=~/dotfiles/bin/urxvt_local
if [ -e $fpath ]; then
    echo "${fpath} is already there."
else
    cat << EOS > ${fpath}
#!/bin/bash
# you can put some options for local machine, since this file is git-ignored.
urxvt_auto
EOS
    chmod +x ${fpath}
fi

# gnome
## basic settings
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

## install language support
langsup=$(check-language-support)
if [ -n "$langsup" ]; then
    read -q ans\?'Install language support? (may not necessary) [y/N]:'
    echo
    if [ $ans = 'y' ]; then
        sudo -E apt install $langsup
    fi
fi

## load gnome-terminal settings
cd ./gnome && ./gnome-term-load.sh && cd ..

# i3
## To avoid nautilus hang-up on i3 session (occurs on Ubuntu 16.04)
gsettings set org.gnome.desktop.background show-desktop-icons false

## install ibus-mozc
dpkg-query -W ibus-mozc &> /dev/null
if [ "$?" != 0 ]; then
    sudo -E apt install ibus-mozc
fi

## xsession for xrdp
if [ ! -e ~/.xsession ]; then
    ln -s ~/dotfiles/i3/xsession ~/.xsession
fi
