#!/bin/bash

# gnome-settings
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

# install language support
langsup=$(check-language-support)
if [ -n "$langsup" ]; then
    sudo -E apt install $langsup
fi

# set launcher icon for matlab
target=${HOME}/.local/share/applications/matlab.desktop
matlab=${HOME}/opt/matlab
if [ -d ${matlab} ]; then
    sed "s@<HOME>@${HOME}@g" matlab.desktop > $target
    # chmod u+x $target
else
    echo "no MATLAB directory (${matlab}) found"
fi

# load gnome-terminal settings
./gnome-term-load.sh
